# 输入的特征数量，包含定量变量和定性变量，定性变量放在后面。所有的定性变量需要在category_counts中指定类别数量
input_size: 9
# 输出的特征数量
output_size: 1
# 编码器的时间步长
num_encoder_steps: 10
# 输出的分位数
quantiles: [0.5]

# 定性变量的类别数量。若有多个定性变量，则列表设定多个值
category_counts: [49]

# 观测变量索引。偏移相对于input
input_obs_loc: [0]
# 静态变量索引。偏移相对于input
static_input_loc: [8]
# 已知的定量变量索引。偏移相对于input中的定量变量
known_regular_inputs: [7]
# 已知的定性变量索引。偏移相对于input中的定性变量
known_categorical_inputs: []


hidden_layer_size: 160
dropout_rate: 0.1
num_heads: 4
