# 模型本身参数
model:
  input_size:  9
  hidden_size: 1024
  output_size: 6
  num_lstm_layers: 3

# 训练器参数 (更多参数参考trainer/trainer.py TrainerArguments类)
trainer:
  device: "cuda"
  output_path: "method/LSTM/output"
  train_epochs: 100
  lr_rate: 0.001
  
  val_interval_monitor: "epoch"
  val_interval: 1

  callback:
    # 保存验证误差最小的模型
    - type: "CheckpointManager"
      path: "best_model"
      interval_monitor: "val_step"
      interval: 1
      monitor: "val_loss"
      monitor_mode: "min"
      max_checkpoints: 3

# 数据集参数
datasets:
  input_steps: [0,12]
  label_steps: [12,13]
  data_path: "data/hgjj/data.pkl"

# 评估参数
eval:
  checkpoint_path: "method/LSTM/output/best_model"
  batch_size: 32
  output_path: "method/LSTM/result"
